"""create service tables

Revision ID: 44ccea43c977
Revises: 
Create Date: 2024-08-28 12:18:41.808595

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44ccea43c977"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("coffee_shop_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_menu_item_coffee_shop_id"),
        "menu_item",
        ["coffee_shop_id"],
        unique=False,
    )
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("issue_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "IN_PROGRESS", "COMPLETED", "CLOSED", name="orderstatus"
            ),
            nullable=False,
        ),
        sa.Column("issuer_id", sa.Integer(), nullable=False),
        sa.Column("assigner_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_assigner_id"), "order", ["assigner_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_customer_id"), "order", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_order_issuer_id"), "order", ["issuer_id"], unique=False)
    op.create_table(
        "order_item",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["menu_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("order_id", "item_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_item")
    op.drop_index(op.f("ix_order_issuer_id"), table_name="order")
    op.drop_index(op.f("ix_order_customer_id"), table_name="order")
    op.drop_index(op.f("ix_order_assigner_id"), table_name="order")
    op.drop_table("order")
    op.drop_index(op.f("ix_menu_item_coffee_shop_id"), table_name="menu_item")
    op.drop_table("menu_item")
    # ### end Alembic commands ###
